server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/ead-notification
    username: postgres
    password: adminnotification
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
      properties:
        hibernate:
          show_slq: true